export const oceanResponses = [
  { keywords: ["shark", "sharks"], response: "Sharks have existed for over 400 million years, long before trees appeared on Earth." },
  { keywords: ["octopus", "octopuses"], response: "Octopuses have three hearts, blue blood, and are among the most intelligent invertebrates." },
  { keywords: ["seahorse"], response: "Seahorses are unique: males carry the babies and give birth to live young." },
  { keywords: ["coral", "reef", "reefs"], response: "Coral reefs are biodiversity hotspots, home to thousands of marine species." },
  { keywords: ["dolphin", "dolphins"], response: "Dolphins are social mammals that communicate using clicks and whistles and sleep with one eye open." },
  { keywords: ["deep ocean", "deep sea", "trench", "mariana"], response: "The Mariana Trench is the deepest ocean point, over 36,000 feet deep." },
  { keywords: ["fish"], response: "Some fish can fly, change gender, or even survive in extreme conditions in the deep sea." },
  { keywords: ["starfish", "sea star"], response: "Starfish can regenerate lost arms, and some species can regrow an entire new starfish from one arm." },
  { keywords: ["ocean", "sea"], response: "The ocean covers 71% of Earth's surface and remains largely unexplored." },
  { keywords: ["yongala", "shipwreck"], response: "The Yongala Shipwreck in Australia sank in 1911 and is now a thriving coral reef ecosystem." },
  { keywords: ["neptune reef", "neptune memorial reef"], response: "Neptune Memorial Reef in Miami is an artificial reef made from human remains and cement, supporting marine life." },
  { keywords: ["blue corner"], response: "The Blue Corner Wall in Palau is a top diving site, known for strong currents and rich marine biodiversity." },
  { keywords: ["sandfalls", "cabo sandfalls"], response: "Sandfalls in Cabo, Mexico are underwater phenomena where sand cascades down a shelf like a waterfall." },
  { keywords: ["barrier reef", "great barrier reef"], response: "The Great Barrier Reef is the world's largest coral reef system and a UNESCO World Heritage site." },
  { keywords: ["underwater waterfall", "mauritius waterfall"], response: "The underwater waterfall in Mauritius is an optical illusion created by sand and silt movement." },
  { keywords: ["heracleion", "cleopatra"], response: "Cleopatra’s Heracleion in Egypt was a submerged city discovered in 2000, full of ancient treasures." },
  { keywords: ["port royal", "jamaica"], response: "Port Royal was once a sinful city in Jamaica, submerged under water after an earthquake in 1692." },
  { keywords: ["museum", "underwater museum", "mexico museum"], response: "The Underwater Museum in Mexico has over 470 submerged statues for snorkelers to explore." },
  { keywords: ["green lake", "austria"], response: "Green Lake in Austria floods a park every summer, creating a unique underwater landscape for divers." },
  { keywords: ["dean’s blue hole"], response: "Dean’s Blue Hole is the world’s deepest saltwater blue hole, located in Long Island, Bahamas." },
  { keywords: ["zhemchug canyon"], response: "Zhemchug Canyon is the largest underwater canyon in the world, located in the Bering Sea." },
  { keywords: ["shark", "sharks", "great white", "hammerhead", "tiger shark", "whale shark", "bull shark", "makos", "reef shark"], response: "Sharks have existed for over 400 million years, long before trees appeared on Earth." },
  { keywords: ["whale shark"], response: "The whale shark is the largest fish on Earth, growing up to 40 feet long and feeding only on plankton." },
  { keywords: ["hammerhead"], response: "Hammerhead sharks use their wide heads to improve sensory perception while hunting prey." },
  { keywords: ["megalodon"], response: "The megalodon was an ancient giant shark, possibly reaching 60 feet in length — the largest predator to ever live." },
  { keywords: ["octopus", "octopuses", "octopi"], response: "Octopuses have three hearts, blue blood, and are among the most intelligent invertebrates." },
  { keywords: ["squid", "giant squid", "colossal squid"], response: "Giant squids can grow longer than a bus and inspired myths of the legendary Kraken." },
  { keywords: ["cuttlefish"], response: "Cuttlefish can change both color and texture to blend with surroundings — masters of camouflage." },
  { keywords: ["fish", "fishes", "clownfish", "tuna", "salmon", "anglerfish", "flying fish"], response: "Some fish can fly, change gender, or even survive in extreme conditions in the deep sea." },
  { keywords: ["anglerfish"], response: "Female anglerfish use bioluminescent lures to attract prey in the dark ocean depths." },
  { keywords: ["clownfish"], response: "Clownfish live in sea anemones — protected by a special mucus coating that prevents stings." },
  { keywords: ["dolphin", "dolphins", "orca", "killer whale"], response: "Dolphins are social mammals that communicate using clicks and whistles and sleep with one eye open." },
  { keywords: ["whale", "blue whale", "humpback whale", "sperm whale", "beluga"], response: "The blue whale is the largest animal ever known — its tongue alone weighs as much as an elephant." },
  { keywords: ["narwhal"], response: "Narwhals are called the unicorns of the sea — their long tusks are actually elongated teeth." },
  { keywords: ["jellyfish", "jellyfishes"], response: "Jellyfish have no brains or hearts and have drifted in Earth’s oceans for over 500 million years." },
  { keywords: ["starfish", "sea star"], response: "Starfish can regenerate lost arms — and some can regrow an entire body from one arm." },
  { keywords: ["sea urchin"], response: "Sea urchins use tiny tube feet for movement and feed on algae — crucial for reef balance." },
  { keywords: ["sea cucumber"], response: "Sea cucumbers can eject their internal organs to escape predators — and later regenerate them." },
  { keywords: ["turtle", "sea turtle", "loggerhead", "leatherback", "green turtle"], response: "Sea turtles navigate thousands of miles and return to the same beach to lay their eggs." },
  { keywords: ["penguin", "penguins"], response: "Penguins are flightless birds that use their wings as flippers — expert swimmers!" },
  { keywords: ["seal", "seals", "sea lion", "walrus"], response: "Seals and sea lions are marine mammals that spend time both on land and in water." },
  { keywords: ["manatee", "dugong"], response: "Manatees, also called sea cows, are gentle herbivores often mistaken for mermaids by sailors." },
  { keywords: ["ocean", "sea", "seas", "marine"], response: "The ocean covers 71% of Earth's surface and remains largely unexplored." },
  { keywords: ["depth", "deep ocean", "deep sea", "trench", "mariana", "mariana trench"], response: "The Mariana Trench is the deepest point on Earth, over 36,000 feet deep." },
  { keywords: ["waves", "currents"], response: "Ocean currents regulate Earth's climate by distributing heat around the globe." },
  { keywords: ["tides", "high tide", "low tide"], response: "Tides are caused by the gravitational pull of the moon and the sun on Earth's oceans." },
  { keywords: ["salt", "salinity"], response: "The ocean's salt comes from rocks on land that have eroded over millions of years." },
  { keywords: ["ocean floor", "sea floor", "seabed"], response: "The ocean floor features mountains, volcanoes, trenches, and vast plains — just like land!" },
  { keywords: ["temperature", "cold water", "warm water"], response: "Deep ocean waters can be near freezing, even under tropical seas." },
  { keywords: ["pressure", "deep pressure"], response: "Pressure increases by 1 atmosphere for every 10 meters you descend underwater." },
  { keywords: ["great barrier reef", "barrier reef", "reef"], response: "The Great Barrier Reef is the world’s largest coral reef system and a UNESCO World Heritage Site." },
  { keywords: ["bermuda triangle"], response: "The Bermuda Triangle is infamous for mysterious disappearances of ships and aircraft." },
  { keywords: ["blue hole", "belize blue hole", "dean’s blue hole"], response: "Dean’s Blue Hole in the Bahamas is the world’s deepest known blue hole." },
  { keywords: ["maldives", "fiji", "seychelles"], response: "These tropical islands are surrounded by coral reefs and clear turquoise waters." },
  { keywords: ["galapagos"], response: "The Galápagos Islands are home to unique species that inspired Darwin’s theory of evolution." },
  { keywords: ["yongala", "shipwreck"], response: "The Yongala Shipwreck in Australia sank in 1911 and is now a thriving coral reef ecosystem." },
  { keywords: ["titanic"], response: "The Titanic sank in 1912 in the North Atlantic Ocean and lies about 12,500 feet underwater." },
  { keywords: ["bismarck", "lusitania", "andrea doria"], response: "These famous shipwrecks rest deep beneath the sea, serving as underwater time capsules." },
  { keywords: ["heracleion", "cleopatra"], response: "Cleopatra’s Heracleion in Egypt was a submerged city discovered in 2000, full of ancient treasures." },
  { keywords: ["port royal", "jamaica"], response: "Port Royal was once a sinful pirate city, submerged by an earthquake in 1692." },
  { keywords: ["atlantis"], response: "Atlantis is a legendary lost city said to have sunk beneath the sea thousands of years ago." },
  { keywords: ["coral", "coral reef", "reefs"], response: "Coral reefs are biodiversity hotspots, home to 25% of all marine species." },
  { keywords: ["plankton", "phytoplankton"], response: "Plankton produce over half of Earth's oxygen — tiny but vital to life." },
  { keywords: ["kelp", "seaweed"], response: "Kelp forests are underwater jungles that shelter countless marine creatures." },
  { keywords: ["underwater waterfall", "mauritius waterfall"], response: "The underwater waterfall near Mauritius is an optical illusion created by sand movement." },
  { keywords: ["sandfalls", "cabo sandfalls"], response: "Sandfalls in Cabo are underwater cascades where sand flows like waterfalls." },
  { keywords: ["bioluminescence", "glow water", "glowing beach"], response: "Bioluminescent plankton make some beaches glow blue at night — nature’s magic light show!" },
  { keywords: ["tsunami"], response: "Tsunamis are giant sea waves caused by underwater earthquakes or volcanic eruptions." },
  { keywords: ["whirlpool", "maelstrom"], response: "Whirlpools form when opposing currents meet — massive ones are called maelstroms." },
  { keywords: ["typhoon", "hurricane", "cyclone"], response: "Tropical storms form over warm oceans, gaining strength from evaporating seawater." },
  { keywords: ["diving", "scuba", "diver"], response: "Scuba divers explore the underwater world using tanks filled with compressed air." },
  { keywords: ["submarine", "submersible"], response: "Submarines allow humans to explore the darkest and deepest ocean zones safely." },
  { keywords: ["sonar"], response: "SONAR uses sound waves to detect objects underwater — essential for mapping and navigation." },
  { keywords: ["marine biologist"], response: "Marine biologists study life in the ocean, from microscopic plankton to giant whales." },
  { keywords: ["exploration", "expedition", "ocean explorer"], response: "Less than 20% of the ocean floor has been mapped — there’s still so much to discover!" },
  { keywords: ["climate", "warming", "pollution", "acidification"], response: "Oceans absorb 30% of carbon dioxide and 90% of excess heat from global warming." },
  { keywords: ["plastic", "plastic pollution", "microplastics"], response: "Millions of tons of plastic enter the ocean yearly — harming marine life and ecosystems." },
  { keywords: ["oil spill"], response: "Oil spills cause massive damage to marine habitats, taking decades to recover." },
  { keywords: ["coral bleaching"], response: "When water is too warm, corals expel algae, turning white — this is coral bleaching." },
  { keywords: ["marine conservation", "save ocean"], response: "Marine conservation efforts aim to protect the ocean’s health and biodiversity." },
  { keywords: ["neptune reef", "neptune memorial reef"], response: "Neptune Memorial Reef in Miami is an artificial reef built from human remains and cement." },
  { keywords: ["underwater museum", "mexico museum", "sculpture reef"], response: "The Underwater Museum in Mexico has over 470 submerged statues." },
  { keywords: ["green lake", "austria"], response: "Green Lake in Austria floods a park every summer, creating an underwater wonderland." },
  { keywords: ["zhemchug canyon"], response: "Zhemchug Canyon in the Bering Sea is the world’s largest underwater canyon." },
  { keywords: ["blue corner"], response: "The Blue Corner in Palau is one of the best dive spots in the world for shark sightings." },
  { keywords: ["kraken"], response: "The Kraken is a legendary sea monster said to dwell off Norway’s coast, likely inspired by giant squids." },
  { keywords: ["mermaid", "mermaids"], response: "Mermaid myths likely originated from sightings of manatees or dugongs by sailors." },
  { keywords: ["poseidon", "neptune"], response: "Poseidon (Neptune in Roman myth) is the god of the sea, earthquakes, and horses." },
  { keywords: ["black smoker", "hydrothermal vent"], response: "Hydrothermal vents spew mineral-rich water supporting alien-like deep-sea creatures." },
  { keywords: ["sea level rise"], response: "Global warming is causing polar ice melt, leading to rising sea levels worldwide." },
  { keywords: ["pressure zone", "midnight zone", "abyss"], response: "The midnight zone is so dark that no sunlight reaches it — only bioluminescence glows." },
  { keywords: ["ocean layers"], response: "The ocean has five layers — sunlight, twilight, midnight, abyssal, and hadal zones." },
  { keywords: ["oxygen", "carbon cycle"], response: "Oceans produce over half of Earth’s oxygen and store vast amounts of carbon." },
  { keywords: ["shark", "sharks"], response: "Sharks have existed for over 400 million years, long before trees appeared on Earth." },
  { keywords: ["great white", "white shark"], response: "The great white shark can detect a drop of blood in 25 gallons of water and sense prey from over a mile away." },
  { keywords: ["hammerhead"], response: "Hammerhead sharks have a unique head shape that allows them to have 360-degree vision and better sensory detection." },
  { keywords: ["whale shark"], response: "Whale sharks are the largest fish in the world, reaching lengths of over 40 feet." },
  { keywords: ["octopus", "octopuses"], response: "Octopuses have three hearts, blue blood, and can change both color and texture to camouflage." },
  { keywords: ["cuttlefish"], response: "Cuttlefish are masters of disguise, able to change color, pattern, and texture in milliseconds." },
  { keywords: ["squid"], response: "Some squid species, like the giant squid, can grow up to 43 feet long and live in deep ocean zones." },
  { keywords: ["seahorse"], response: "Seahorses are unique: males carry the babies and give birth to live young." },
  { keywords: ["starfish", "sea star"], response: "Starfish can regenerate lost arms, and some species can regrow an entirely new starfish from one arm." },
  { keywords: ["clownfish"], response: "Clownfish live in symbiosis with sea anemones, gaining protection while cleaning the anemone." },
  { keywords: ["dolphin", "dolphins"], response: "Dolphins are social mammals that communicate using clicks and whistles and sleep with one eye open." },
  { keywords: ["orca", "killer whale"], response: "Orcas are apex predators and can hunt in coordinated pods, even preying on whales much larger than themselves." },
  { keywords: ["coral", "reef", "reefs"], response: "Coral reefs are biodiversity hotspots, home to thousands of marine species." },
  { keywords: ["great barrier reef"], response: "The Great Barrier Reef is the world's largest coral reef system and a UNESCO World Heritage site." },
  { keywords: ["mariana trench", "deep ocean", "deep sea", "trench"], response: "The Mariana Trench is the deepest ocean point, over 36,000 feet deep." },
  { keywords: ["yongala", "shipwreck"], response: "The Yongala Shipwreck in Australia sank in 1911 and is now a thriving coral reef ecosystem." },
  { keywords: ["neptune reef", "neptune memorial reef"], response: "Neptune Memorial Reef in Miami is an artificial reef made from human remains and cement, supporting marine life." },
  { keywords: ["blue corner"], response: "The Blue Corner Wall in Palau is a top diving site, known for strong currents and rich marine biodiversity." },
  { keywords: ["sandfalls", "cabo sandfalls"], response: "Sandfalls in Cabo, Mexico are underwater phenomena where sand cascades down a shelf like a waterfall." },
  { keywords: ["underwater waterfall", "mauritius waterfall"], response: "The underwater waterfall in Mauritius is an optical illusion created by sand and silt movement." },
  { keywords: ["heracleion", "cleopatra"], response: "Cleopatra’s Heracleion in Egypt was a submerged city discovered in 2000, full of ancient treasures." },
  { keywords: ["port royal", "jamaica"], response: "Port Royal was once a sinful city in Jamaica, submerged under water after an earthquake in 1692." },
  { keywords: ["museum", "underwater museum", "mexico museum"], response: "The Underwater Museum in Mexico has over 470 submerged statues for snorkelers to explore." },
  { keywords: ["green lake", "austria"], response: "Green Lake in Austria floods a park every summer, creating a unique underwater landscape for divers." },
  { keywords: ["dean’s blue hole"], response: "Dean’s Blue Hole is the world’s deepest saltwater blue hole, located in Long Island, Bahamas." },
  { keywords: ["zhemchug canyon"], response: "Zhemchug Canyon is the largest underwater canyon in the world, located in the Bering Sea." },
  { keywords: ["anglerfish"], response: "Anglerfish use a bioluminescent lure to attract prey in the pitch-black depths of the ocean." },
  { keywords: ["manta ray"], response: "Manta rays can have wingspans up to 23 feet and are known for their graceful underwater acrobatics." },
  { keywords: ["jellyfish"], response: "Some jellyfish are biologically immortal, reverting back to their polyp stage after reaching adulthood." },
  { keywords: ["lionfish"], response: "Lionfish are invasive species in the Atlantic and Caribbean, spreading rapidly due to lack of predators." },
  { keywords: ["pufferfish"], response: "Pufferfish can inflate themselves to deter predators and contain tetrodotoxin, a potent neurotoxin." },
  { keywords: ["manatee", "sea cow"], response: "Manatees are gentle marine mammals that graze on underwater plants and can weigh over 1,000 pounds." },
  { keywords: ["walrus"], response: "Walruses use their long tusks to pull themselves onto ice and fight for territory or mates." },
  { keywords: ["penguin"], response: "Penguins are flightless birds that thrive in cold oceanic environments and excellent swimmers." },
  { keywords: ["sea turtle", "turtle"], response: "Sea turtles can live up to 80 years and navigate thousands of miles using Earth’s magnetic fields." },
  { keywords: ["narwhal"], response: "Narwhals are known as 'unicorns of the sea' due to their long, spiraled tusks." },
  { keywords: ["beluga"], response: "Beluga whales are social and known as 'canaries of the sea' for their wide range of vocalizations." },
  { keywords: ["squid giant", "giant squid"], response: "The giant squid can reach lengths of up to 43 feet and was first filmed alive in the deep ocean in 2012." },
  { keywords: ["coelacanth"], response: "Coelacanths were thought extinct for 66 million years until rediscovered off South Africa in 1938." },
  { keywords: ["krill"], response: "Krill are tiny shrimp-like creatures forming huge swarms that feed whales and many marine animals." },
  { keywords: ["plankton"], response: "Plankton are microscopic organisms forming the base of the ocean food chain." },
  { keywords: ["sea sponge"], response: "Sea sponges are simple, filter-feeding organisms that can live for thousands of years." },
  { keywords: ["moray eel"], response: "Moray eels hide in crevices and have a second pharyngeal jaw to help catch prey." },
  { keywords: ["coral bleaching"], response: "Coral bleaching occurs when corals expel algae due to stress, often from warming oceans." },
  { keywords: ["bioluminescence"], response: "Many marine creatures produce light through bioluminescence to attract prey, mates, or deter predators." },
  { keywords: ["tidal bore"], response: "Tidal bores are waves traveling upstream in rivers due to high tides entering the river mouths." },
  { keywords: ["whirlpool"], response: "Whirlpools form from powerful circular currents in oceans or rivers." },
  { keywords: ["underwater volcano"], response: "Submarine volcanoes can form islands and release mineral-rich water supporting unique ecosystems." },
  { keywords: ["hydrothermal vent", "black smoker"], response: "Hydrothermal vents release superheated water, supporting life in complete darkness." },
  { keywords: ["sargassum"], response: "Sargassum is floating seaweed that creates habitats for many marine species in the Atlantic Ocean." },
  { keywords: ["ocean acidification"], response: "Ocean acidification occurs when CO₂ is absorbed by seawater, affecting shell-building marine life." },
  { keywords: ["kelp forest"], response: "Kelp forests are underwater ecosystems that support fish, sea otters, and invertebrates." },
  { keywords: ["mangrove"], response: "Mangroves protect coastlines, filter water, and provide nurseries for many fish species." },
  { keywords: ["plastic pollution"], response: "Plastic pollution threatens marine life, as animals mistake it for food or become entangled." },
  { keywords: ["oil spill"], response: "Oil spills harm ecosystems by coating animals and plants and disrupting marine food chains." },
  { keywords: ["tsunami"], response: "Tsunamis are massive waves caused by underwater earthquakes, volcanic eruptions, or landslides." },
  { keywords: ["humpback whale"], response: "Humpback whales migrate thousands of miles each year and produce complex songs to communicate." },
  { keywords: ["blue whale"], response: "The blue whale is the largest animal ever, growing up to 100 feet and weighing 200 tons." },
  { keywords: ["sperm whale"], response: "Sperm whales can dive over 7,000 feet and hold their breath for more than an hour." },
  { keywords: ["orca killer whale"], response: "Orcas are apex predators hunting in pods and showing complex social behaviors." },
  { keywords: ["lobster"], response: "Lobsters can live over 50 years and grow throughout their lives by molting their shells." },
  { keywords: ["crab"], response: "Crabs have ten legs, and some species can walk sideways using specialized joints." },
  { keywords: ["shrimp"], response: "Shrimp are vital in marine food chains and can communicate using tail flicks or sounds." },
  { keywords: ["jellyfish box", "box jellyfish"], response: "Box jellyfish are extremely venomous and can cause cardiac arrest in humans." },
  { keywords: ["sea snake"], response: "Sea snakes are highly venomous reptiles adapted to marine life, breathing air at the surface." },
  { keywords: ["mantis shrimp"], response: "Mantis shrimps have the fastest strike in the animal kingdom and can break shells with their claws." },
  { keywords: ["anglerfish deep", "angler fish"], response: "Anglerfish use a glowing lure to attract prey in the deep ocean darkness." },
  { keywords: ["flying fish"], response: "Flying fish can glide above water for distances up to 200 meters to escape predators." },
  { keywords: ["ocean current"], response: "Ocean currents regulate climate by moving warm and cold water across the globe." },
  { keywords: ["gulf stream"], response: "The Gulf Stream is a warm Atlantic Ocean current that influences weather patterns in Europe and North America." },
  { keywords: ["antarctic"], response: "The Antarctic Ocean is the coldest and contains some of the most unique marine life on Earth." },
  { keywords: ["arctic"], response: "The Arctic Ocean is home to polar bears, walruses, narwhals, and resilient cold-adapted marine life." },
  { keywords: ["phytoplankton"], response: "Phytoplankton are tiny organisms performing photosynthesis and producing half of Earth's oxygen." },
  { keywords: ["zooplankton"], response: "Zooplankton feed on phytoplankton and are vital for oceanic food webs." },
  { keywords: ["sea lion"], response: "Sea lions are social mammals known for their loud barking and agility in water." },
  { keywords: ["penguin emperor", "emperor penguin"], response: "Emperor penguins can survive in temperatures as low as -60°C and dive up to 500 meters." },
  { keywords: ["algae"], response: "Marine algae are crucial for oxygen production and forming habitats for fish and invertebrates." },
  { keywords: ["sea otter"], response: "Sea otters use tools like rocks to open shellfish and maintain kelp forest ecosystems." },
  { keywords: ["man o' war"], response: "The Portuguese man o' war is a colony of specialized polyps and has tentacles over 30 feet long." },
  { keywords: ["coral polyp"], response: "Coral polyps are tiny animals that build calcium carbonate skeletons forming reefs." },
  { keywords: ["fossil"], response: "Marine fossils provide evidence of ancient oceans and extinct species." },
  { keywords: ["hydrology"], response: "Ocean hydrology studies the movement, distribution, and properties of seawater." },
  { keywords: ["upwelling"], response: "Upwelling brings nutrient-rich water from deep oceans to the surface, supporting marine life." },
  { keywords: ["downwelling"], response: "Downwelling transports oxygen-rich surface water to deeper layers." },
  { keywords: ["seamount"], response: "Seamounts are underwater mountains formed by volcanic activity, supporting unique ecosystems." },
  { keywords: ["oceanographer"], response: "Oceanographers study oceans, marine life, currents, and the ocean floor." },
  { keywords: ["nautical mile"], response: "A nautical mile equals 1.852 kilometers and is used in marine navigation." },
  { keywords: ["echolocation"], response: "Dolphins and some whales use echolocation to navigate and hunt in the ocean." },
  { keywords: ["submarine"], response: "Submarines can dive deep into the ocean for research, exploration, or military purposes." },
  { keywords: ["ROV"], response: "Remotely Operated Vehicles (ROVs) are used to explore deep-sea environments." },
  { keywords: ["AUV"], response: "Autonomous Underwater Vehicles (AUVs) explore oceans without direct human control." },
  { keywords: ["sonar"], response: "Sonar uses sound waves to detect objects, measure depth, and map the seafloor." },
  { keywords: ["tidal energy"], response: "Tidal energy harnesses the power of ocean tides to generate renewable electricity." },
  { keywords: ["wave energy"], response: "Wave energy converts the motion of ocean waves into electricity." },
  { keywords: ["thermohaline circulation"], response: "The ocean conveyor belt, or thermohaline circulation, distributes heat globally through deep currents." },
  { keywords: ["marine snow"], response: "Marine snow is organic material falling from surface waters, feeding deep-sea ecosystems." },
  { keywords: ["bycatch"], response: "Bycatch refers to unintentional capture of non-target species in fishing operations." },
  { keywords: ["overfishing"], response: "Overfishing threatens fish populations and destabilizes marine ecosystems." },
  { keywords: ["el nino"], response: "El Niño is a climate pattern causing ocean warming, disrupting weather and marine life." },
  { keywords: ["la nina"], response: "La Niña is a climate pattern causing ocean cooling and affects weather patterns globally." },
  { keywords: ["squid vampire", "vampire squid"], response: "The vampire squid lives in oxygen-poor deep ocean zones and has bioluminescent photophores." },
  { keywords: ["hagfish"], response: "Hagfish produce slime as a defense mechanism and feed on dead or dying animals." },
  { keywords: ["lamprey"], response: "Lampreys are jawless fish that attach to hosts and feed on blood and tissues." },
  { keywords: ["mantle"], response: "In mollusks, the mantle secretes shells and forms the body cavity." },
  { keywords: ["crinoid"], response: "Crinoids are ancient marine animals resembling flowers but are related to sea stars." },
  { keywords: ["urchin"], response: "Sea urchins graze on algae and play a role in maintaining coral reef health." },
  { keywords: ["sand dollar"], response: "Sand dollars are flattened sea urchins living on sandy seabeds." },
  { keywords: ["oyster"], response: "Oysters filter water, improve water quality, and produce pearls." },
  { keywords: ["clam"], response: "Clams are bivalves living in sand or mud and feed by filtering plankton." },
  { keywords: ["mollusk"], response: "Mollusks include snails, clams, squids, and octopuses, showing great diversity." },
  { keywords: ["crustacean"], response: "Crustaceans include crabs, lobsters, shrimps, and krill." },
  { keywords: ["echinoderm"], response: "Echinoderms include starfish, sea urchins, and sea cucumbers, all with radial symmetry." },
  { keywords: ["cnidarian"], response: "Cnidarians include jellyfish, corals, and sea anemones, characterized by stinging cells." },
  { keywords: ["cetacean"], response: "Cetaceans include whales, dolphins, and porpoises, all fully aquatic mammals." },
  { keywords: ["pinniped"], response: "Pinnipeds include seals, sea lions, and walruses, adapted for swimming and land haul-outs." },
  { keywords: ["marine biologist"], response: "Marine biologists study ocean ecosystems, marine life behavior, and conservation." },
  { keywords: ["fathom"], response: "A fathom equals six feet and is used to measure water depth." },
  { keywords: ["bathymetry"], response: "Bathymetry is the study of underwater depth of ocean floors." },
  { keywords: ["continental shelf"], response: "The continental shelf is the submerged edge of continents, rich in marine resources." },
  { keywords: ["abyssal plain"], response: "Abyssal plains are flat deep-ocean floors covered with sediments and hosting unique life forms." },
  { keywords: ["mid-ocean ridge"], response: "Mid-ocean ridges are underwater mountain ranges formed by tectonic activity." },
  { keywords: ["hydrography"], response: "Hydrography studies the physical features of oceans, seas, and rivers." },
  { keywords: ["photic zone"], response: "The photic zone is the sunlight-penetrated upper layer of the ocean where photosynthesis occurs." },
  { keywords: ["aphotic zone"], response: "The aphotic zone is the dark, deep part of the ocean where sunlight cannot reach." },
  { keywords: ["twilight zone", "mesopelagic"], response: "The twilight zone of the ocean is between 200–1,000 meters deep, home to many bioluminescent species." },
  { keywords: ["bathypelagic"], response: "The bathypelagic zone is 1,000–4,000 meters deep, inhabited by large, slow-moving animals." },
  { keywords: ["abyssopelagic"], response: "The abyssopelagic zone extends from 4,000–6,000 meters, extremely cold and high-pressure." },
  { keywords: ["hadalpelagic"], response: "The hadalpelagic zone includes ocean trenches deeper than 6,000 meters." },
  { keywords: ["salinity"], response: "Salinity measures the salt content of seawater, typically around 35 ppt (parts per thousand)."},
  { keywords: ["density ocean"], response: "Ocean density affects circulation and is influenced by temperature and salinity." },
  { keywords: ["wave"], response: "Ocean waves are created mainly by wind blowing across the surface." },
  { keywords: ["tsunami wave"], response: "Tsunamis are long-wavelength waves caused by undersea earthquakes or landslides." },
  { keywords: ["rip current"], response: "Rip currents are strong, narrow currents moving away from the shore, dangerous for swimmers." },
  { keywords: ["eddies"], response: "Eddies are swirling water formations caused by current changes." },
  { keywords: ["upwelling zone"], response: "Upwelling zones bring nutrient-rich deep water to surface, supporting fisheries." },
  { keywords: ["continental slope"], response: "The continental slope connects the continental shelf to the deep ocean floor." },
  { keywords: ["submarine canyon"], response: "Submarine canyons cut into continental slopes, transporting sediments to deep seas." },
  { keywords: ["marine protected area", "MPA"], response: "MPAs are regions where human activity is restricted to protect ecosystems." },
  { keywords: ["overfishing impact"], response: "Overfishing reduces fish populations and disrupts marine food chains." },
  { keywords: ["bycatch effect"], response: "Bycatch harms non-target species, including endangered animals." },
  { keywords: ["coral spawning"], response: "Corals spawn once a year, synchronizing with moon phases to release eggs and sperm." },
  { keywords: ["algal bloom"], response: "Algal blooms can deplete oxygen in water, causing dead zones." },
  { keywords: ["dead zone ocean"], response: "Dead zones are areas with low oxygen levels, often from pollution and runoff." },
  { keywords: ["ocean cleanup"], response: "Ocean cleanup efforts include removing plastic waste and restoring habitats." },
  { keywords: ["oil rig"], response: "Oil rigs extract petroleum from underwater reservoirs, sometimes impacting marine life." },
  { keywords: ["underwater cable"], response: "Underwater cables carry telecommunications and internet data across oceans." },
  { keywords: ["seafloor mapping"], response: "Seafloor mapping uses sonar and satellites to study the ocean floor." },
  { keywords: ["marine debris"], response: "Marine debris includes plastic, metal, and other waste polluting oceans." },
  { keywords: ["ocean exploration"], response: "Ocean exploration uncovers new species, geological formations, and shipwrecks." }

];