
export const oceanFacts = [
  "Some fish can change their gender during their lifetime.",
  "Octopuses have three hearts and blue blood.",
  "Seahorses are the only fish where males give birth.",
  "Sharks existed before trees.",
  "The deepest part of the ocean is over 36,000 feet deep.",
  "Clownfish can communicate by making popping and clicking sounds.",
  "Some fish can fly above water for short distances.",
  "Starfish can regenerate lost arms.",
  "Dolphins sleep with one eye open.",
  "The ocean covers more than 70% of Earth's surface.",
  "About 80% of the ocean remains unexplored.",
  "The Great Barrier Reef is the largest living structure on Earth.",
  "The Pacific Ocean is the largest ocean, covering one-third of Earth's surface.",
  "The Mariana Trench is deeper than Mount Everest is tall.",
  "There are underwater lakes and rivers formed by dense brine.",
  "The ocean produces more than half of the world’s oxygen.",
  "Blue whales are the largest animals to have ever lived on Earth.",
  "Jellyfish have existed for over 500 million years.",
  "Sea turtles can live to be over 100 years old.",
  "Some species of squid can grow longer than a school bus.",
  "Marine plankton produce most of the oxygen we breathe.",
  "Coral reefs are home to about 25% of all marine life.",
  "Some coral reefs glow under ultraviolet light.",
  "Hammerhead sharks can see 360 degrees around them.",
  "The Sargasso Sea has no shores; it's defined by ocean currents.",
  "Some fish use bioluminescence to attract prey or mates.",
  "There are volcanoes erupting under the ocean every day.",
  "Hydrothermal vents support ecosystems without sunlight.",
  "The ocean absorbs about 30% of human-made carbon dioxide.",
  "Sea otters hold hands while sleeping so they don’t drift apart.",
  "There are mountains and valleys under the ocean larger than on land.",
  "Giant clams can weigh more than 200 kilograms.",
  "The ocean’s average depth is around 12,100 feet.",
  "There are rivers and waterfalls beneath the ocean’s surface.",
  "Some underwater creatures are transparent for camouflage.",
  "Antarctica has hidden lakes beneath its ice connected to the ocean.",
  "The ‘Black Sea’ got its name from the color of its deep sediments.",
  "Sea cucumbers clean the ocean floor by eating debris.",
  "Some fish, like parrotfish, create sand by chewing coral.",
  "Marine snow is a constant shower of organic material falling to the ocean floor.",
  "The ocean floor is mapped less than the surface of Mars.",
  "Sound travels over four times faster in water than in air.",
  "Some whales can communicate across entire ocean basins.",
  "The Greenland shark can live over 400 years.",
  "There’s enough salt in the ocean to cover all continents 500 feet deep.",
  "The Dead Sea is actually a hypersaline lake.",
  "Bioluminescent bays glow naturally at night in places like Puerto Rico.",
  "Sea sponges are among the oldest multicellular organisms on Earth.",
  "The ocean has its own weather systems and currents.",
  "The Gulf Stream carries warm water from the Gulf of Mexico to Europe.",
  "The Titanic sank in the North Atlantic Ocean in 1912.",
  "The ocean floor is constantly moving due to tectonic plates.",
  "Some deep-sea fish can survive immense pressure that would crush a submarine.",
  "Narwhals are real animals, often called the 'unicorns of the sea.'",
  "Crabs can walk in any direction, but usually move sideways.",
  "Mantis shrimp have the most complex eyes in the animal kingdom.",
  "Some fish can breathe air when water levels drop.",
  "The giant squid was once thought to be a mythical creature.",
  "Kelp forests can grow up to two feet per day.",
  "A tsunami can travel across the entire ocean in less than a day.",
  "The ocean contains 20 million tons of gold, mostly dissolved.",
  "The Arctic Ocean is the smallest and shallowest ocean.",
  "Some fish, like the mudskipper, can walk on land.",
  "Dolphins have unique signature whistles to identify each other.",
  "The sea floor has canyons deeper than the Grand Canyon.",
  "Oceans moderate Earth’s climate by absorbing heat.",
  "The Indian Ocean is the warmest ocean on Earth.",
  "There are underwater mountain ranges called mid-ocean ridges.",
  "Some species of eels spend part of their life in freshwater and part in the sea.",
  "Phytoplankton are the ocean’s main oxygen producers.",
  "Seaweed farms are used for food, fuel, and medicine.",
  "The average temperature of the ocean is about 39°F (4°C).",
  "There are underwater volcanoes called seamounts.",
  "Whale songs can travel hundreds of miles underwater.",
  "The ocean is home to around 230,000 known species.",
  "There are underwater waterfalls, like the one off the coast of Mauritius.",
  "Barnacles are crustaceans, not mollusks.",
  "Electric eels can produce shocks up to 600 volts.",
  "The ocean’s tides are caused by the gravitational pull of the moon and sun.",
  "Deep-sea vents can reach temperatures of over 750°F.",
  "Some sea snakes can hold their breath for up to eight hours.",
  "Manatees are closely related to elephants.",
  "The pressure at the bottom of the Mariana Trench is over 1,000 times greater than at sea level.",
  "Sea urchins have no bones but can live for decades.",
  "There are more artifacts on the ocean floor than in all the world’s museums.",
  "The ocean’s blue color is due to the absorption of red light wavelengths.",
  "Some shrimp can snap their claws so fast it creates a sonic boom.",
  "Sailors once believed the ocean’s glow was caused by spirits.",
  "The ocean floor has more fossils than land surfaces.",
  "Plastic waste has been found even in the deepest trenches.",
  "Whale sharks are gentle filter feeders despite their size.",
  "The Bermuda Triangle has inspired countless maritime myths.",
  "Bioluminescent plankton can make waves glow at night.",
  "Sea lions can dive over 800 feet deep.",
  "There are underwater “deserts” with very little life called abyssal plains.",
  "Deep-sea jellyfish can turn invisible when threatened.",
  "The longest mountain range on Earth is underwater — the Mid-Ocean Ridge.",
  "The ocean currents act like a conveyor belt for global heat.",
  "Deep-sea anglerfish use glowing lures to attract prey.",
  "Orcas are the largest members of the dolphin family.",
  "Penguins are excellent divers, reaching depths of over 1,500 feet.",
  "Some sea creatures can live for months without food.",
  "The first underwater photograph was taken in 1856.",
  "The Pacific Ocean contains around 25,000 islands.",
  "The ocean’s oldest known animal is the quahog clam, which can live over 500 years.",
  "Marine animals like whales use echolocation to navigate.",
  "Giant tube worms thrive in boiling hot hydrothermal vents.",
  "The ocean contains 97% of the planet’s water.",
  "The Gulf of Mexico’s “Dead Zone” is caused by oxygen depletion.",
  "The world’s largest coral reef system can be seen from space.",
  "Some fish migrate thousands of miles each year.",
  "Sailfish are the fastest fish in the ocean, reaching speeds of 68 mph.",
  "There are underwater ice crystals called brinicles that freeze marine life.",
  "Some sharks glow in the dark.",
  "Dolphins use teamwork to catch fish efficiently.",
  "Coral bleaching occurs when corals expel algae due to stress.",
  "The Pacific Ring of Fire has thousands of submarine volcanoes.",
  "The ocean’s salinity varies depending on rainfall and evaporation.",
  "The Atlantic Ocean is growing wider by about 1 inch per year.",
  "The ocean’s surface reflects only about 5% of sunlight.",
  "Whale feces play a major role in ocean nutrient cycling.",
  "The loudest sound ever recorded came from an iceberg breaking apart underwater.",
  "There are entire underwater forests made of kelp and seagrass.",
  "Deep-sea explorers use remotely operated vehicles to study marine life.",
  "Some fish migrate vertically daily, rising at night and sinking by day.",
  "The sea anemone is related to the jellyfish.",
  "Some coral reefs are thousands of years old.",
  "Polar bears can swim over 60 miles without rest.",
  "The Dead Sea is nearly 10 times saltier than normal seawater.",
  "The Baltic Sea has both fresh and saltwater layers.",
  "The word “ocean” comes from the Greek god Oceanus.",
  "The Pacific Ocean’s name means “peaceful sea.”",
  "Sailors once navigated using stars and ocean currents.",
  "Seaweed produces iodine used in medicine.",
  "There are over 500 known species of sharks.",
  "Some octopuses use coconut shells as shelter.",
  "The sea floor expands as magma rises through mid-ocean ridges.",
  "Oceans have zones based on depth: sunlight, twilight, midnight, abyss, and trenches.",
  "Whales can sleep vertically or horizontally in the water.",
  "Ocean tides can generate renewable energy.",
  "The Mediterranean Sea connects to the Atlantic through the Strait of Gibraltar.",
  "Sea snakes give birth in the water and never go on land.",
  "Swordfish can heat their eyes to improve vision in deep water.",
  "The ocean’s oldest fossils date back over 3 billion years.",
  "Some fish produce antifreeze proteins to survive in icy waters.",
  "The Red Sea was named for seasonal blooms of algae.",
  "Coral polyps are animals, not plants.",
  "There are underwater ruins like Heracleion, the Egyptian Atlantis.",
  "The Caribbean Sea is home to the second-largest barrier reef.",
  "There are more microorganisms in the ocean than stars in the galaxy.",
  "Fish scales inspired the design of body armor.",
  "Sea stars have no brains or blood; they use seawater to move nutrients.",
  "The first oceanographic expedition was HMS Challenger (1872–1876).",
  "Some jellyfish species are considered biologically immortal.",
  "The ocean’s pressure increases by one atmosphere every 10 meters of depth.",
  "Ocean trenches form where tectonic plates collide.",
  "Killer whales are apex predators with no natural enemies.",
  "Dolphins have been trained by navies for rescue missions.",
  "Many ocean fish use countershading — dark on top, light on bottom — for camouflage.",
  "The Pacific garbage patch is twice the size of Texas.",
  "Seagrass meadows capture carbon faster than tropical forests.",
  "There are underwater sinkholes known as blue holes.",
  "Deep-sea creatures often have slow metabolisms to conserve energy.",
  "The deepest scuba dive ever recorded reached over 1,000 feet.",
  "The first submarine was invented in the 1600s.",
  "Oceanic crust is thinner but denser than continental crust.",
  "The sea floor has vents that spew superheated water and minerals.",
  "The Southern Ocean surrounds Antarctica.",
  "Seals can dive for over two hours without surfacing.",
  "The coelacanth, a ‘living fossil,’ was once thought extinct for 65 million years.",
  "Ocean acidification is caused by excess carbon dioxide absorption.",
  "The ocean’s “twilight zone” extends from 200 to 1,000 meters deep.",
  "The deepest living fish was found 8,000 meters below the surface.",
  "The Amazon River discharges enough freshwater to dilute ocean salinity for miles.",
  "Whales feed by filtering tons of water through baleen plates.",
  "Crabs communicate by drumming their claws.",
  "Marine iguanas of the Galápagos are the only sea-going lizards.",
  "Some sea slugs incorporate algae into their own cells to photosynthesize.",
  "Tides can cause small earthquakes along coastlines.",
  "Certain jellyfish can clone themselves.",
  "Dugongs are close relatives of manatees.",
  "Whales migrate thousands of miles each year for breeding.",
  "Giant oarfish are believed to inspire sea serpent legends.",
  "Some sea creatures glow red or green under UV light.",
  "There are ghostly deep-sea creatures like the Dumbo octopus.",
  "Lobsters grow throughout their entire lives.",
  "Sea salt contains trace elements of magnesium and potassium.",
  "Seabirds rely on ocean currents to locate fish.",
  "The North Sea has massive offshore wind farms.",
  "The word “tsunami” comes from Japanese, meaning harbor wave.",
  "Some coral reefs are so large they affect local weather.",
  "Whale milk has the consistency of toothpaste.",
  "Bioluminescent organisms make up 90% of deep-sea creatures.",
  "There are underwater archaeological sites like Pavlopetri in Greece.",
  "Some sea creatures can regenerate entire bodies from fragments.",
  "The ocean has underwater ‘smoke stacks’ called black smokers.",
  "The ocean’s highest tides occur in the Bay of Fundy, Canada.",
  "Sailfish can change color when hunting.",
  "The first person to reach the Mariana Trench was Jacques Piccard in 1960.",
  "The Great Pacific Garbage Patch is not solid — it’s a soup of microplastics.",
  "Some whales sing complex songs that change over time.",
  "The sea absorbs over 90% of excess heat from global warming.",
  "Tidal waves and tsunamis are not the same phenomenon.",
  "Marine fossils are often found in desert rocks that were once underwater.",
  "The average human could only survive seconds at deep-sea pressure.",
  "Some fish have antifreeze-like blood proteins.",
  "Phytoplankton blooms can be seen from space.",
  "Oceans act as Earth’s largest carbon sink.",
  "A single drop of seawater can contain millions of tiny organisms."
];
